# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminAccount', models.CharField(max_length=32)),
                ('adminPassword', models.CharField(max_length=32)),
                ('adminJob', models.CharField(blank=True, max_length=50)),
                ('adminTelephone', models.CharField(blank=True, max_length=12)),
                ('adminEmail', models.CharField(blank=True, max_length=32)),
                ('adminPortrait', models.CharField(blank=True, max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u7ba1\u7406\u5458\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogHead', models.CharField(max_length=100)),
                ('blogPic', models.CharField(blank=True, max_length=100, null=True)),
                ('blogContent', models.TextField(blank=True, null=True)),
                ('introduction', models.CharField(max_length=300)),
                ('isRecommend', models.BooleanField(default=1)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u6587\u7ae0',
                'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='BlogsClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificationName', models.CharField(max_length=32)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='ColumnClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columnName', models.CharField(max_length=32)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateField(auto_now_add=True)),
                ('context', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '\u680f\u76ee\u7c7b\u578b',
                'verbose_name_plural': '\u680f\u76ee\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentsContent', models.TextField(blank=True, null=True)),
                ('peopleName', models.CharField(blank=True, max_length=20)),
                ('peopleEmail', models.CharField(blank=True, max_length=32)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Blogs')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba\u4fe1\u606f',
                'verbose_name_plural': '\u8bc4\u8bba\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='blogsClassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.BlogsClassification'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='columnClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ColumnClass'),
        ),
    ]
