# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnclass',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
